services:
  # nginx:
  #   build: ./proxy/nginx
  #   container_name: nginx
  #   restart: always
  #   ports:
  #     - "80:80"
  #   environment:
  #     - TZ=Asia/Taipei
  #   depends_on:
  #     - front-end
  #     - back-end


  front-end:
    build: ./front-end/angular
    container_name: front-end
    restart: always
    environment:
      - TZ=Asia/Taipei
    ports:
      - "4200:4200"
    depends_on:
      - back-end
      
  back-end:
    build: ./back-end
    container_name: back-end
    restart: always
    environment:
      - TZ=Asia/Taipei
      - BUCKET_NAME=<YOUR_BUCKET_NAME>
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp_key/<YOUR_GCP_KEY>.json
      - GEMINI_API_KEY=<your-gemini-api-key>
      - GCP_PROJECT_ID=<YOUR_GCP_PROJECT_ID>
      - REDIS_HOST=<redis-host>
      - REDIS_PORT=<redis-port>
      - REDIS_PASSWORD=<redis-password>
    ports:
      - "8000:8000"
  
  redis:
    build: ./cache/redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Taipei
      - REDIS_PASSWORD=<redis-password>
    volumes:
      - ./cache/redis/data:/data
    command: >
      sh -c "redis-server /usr/local/etc/redis/redis.conf --requirepass $$REDIS_PASSWORD"