TRAIN_TABLE_FILE_NAME = "train_data_v1.1"
VALIDATION_TABLE_FILE_NAME = "test_data_v1.1"
PREDICTION_TABLE_FILE_NAME = "prediction_data"
REPORT_TABLE_FILE_NAME = "final_expert_report"
PREDICTION_MODEL_FILE_NAME = "Store_Intelligence_Model_v4"
SHAP_DATABASE_FILE_NAME = "SHAP_XGB_Full_Database"